const movieId = [
  {
    "dates": {"maximum": "2024-08-14", "minimum": "2024-07-24"},
    "page": 1,
    "results": [
      {
        "adult": false,
        "backdrop_path": "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
        "genre_ids": [16, 10751, 12, 35],
        "id": 1022789,
        "original_language": "en",
        "original_title": "Inside Out 2",
        "overview":
            "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
        "popularity": 5571.077,
        "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
        "release_date": "2024-06-11",
        "title": "Inside Out 2",
        "video": false,
        "vote_average": 7.668,
        "vote_count": 1955
      },
      {
        "adult": false,
        "backdrop_path": "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
        "genre_ids": [16, 10751, 35, 28],
        "id": 519182,
        "original_language": "en",
        "original_title": "Despicable Me 4",
        "overview":
            "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
        "popularity": 4439.3,
        "poster_path": "/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg",
        "release_date": "2024-06-20",
        "title": "Despicable Me 4",
        "video": false,
        "vote_average": 7.322,
        "vote_count": 349
      },
      {
        "adult": false,
        "backdrop_path": "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
        "genre_ids": [27, 53],
        "id": 646683,
        "original_language": "en",
        "original_title": "The Exorcism",
        "overview":
            "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
        "popularity": 1187.125,
        "poster_path": "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
        "release_date": "2024-05-30",
        "title": "The Exorcism",
        "video": false,
        "vote_average": 4.474,
        "vote_count": 76
      },
      {
        "adult": false,
        "backdrop_path": "/A4JG9mkAjOQ3XNJy2oji1Jr224R.jpg",
        "genre_ids": [878, 28, 35],
        "id": 533535,
        "original_language": "en",
        "original_title": "Deadpool & Wolverine",
        "overview":
            "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
        "popularity": 849.864,
        "poster_path": "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
        "release_date": "2024-07-24",
        "title": "Deadpool & Wolverine",
        "video": false,
        "vote_average": 8.6,
        "vote_count": 11
      },
      {
        "adult": false,
        "backdrop_path": "/7aPrv2HFssWcOtpig5G3HEVk3uS.jpg",
        "genre_ids": [28, 12, 53],
        "id": 718821,
        "original_language": "en",
        "original_title": "Twisters",
        "overview":
            "As storm season intensifies, the paths of former storm chaser Kate Carter and reckless social-media superstar Tyler Owens collide when terrifying phenomena never seen before are unleashed. The pair and their competing teams find themselves squarely in the paths of multiple storm systems converging over central Oklahoma in the fight of their lives.",
        "popularity": 771.648,
        "poster_path": "/bYmszCd9kRbwmXWvxMai9Mm9B92.jpg",
        "release_date": "2024-07-10",
        "title": "Twisters",
        "video": false,
        "vote_average": 7.4,
        "vote_count": 133
      },
      {
        "adult": false,
        "backdrop_path": "/buawWBeKYjYfeiPoS2jIcjOrghZ.jpg",
        "genre_ids": [27, 53],
        "id": 1214509,
        "original_language": "en",
        "original_title": "In a Violent Nature",
        "overview":
            "The enigmatic resurrection, rampage, and retribution of an undead monster in a remote wilderness unleashes an iconic new killer after a locket is removed from a collapsed fire tower that entombed its rotting corpse.",
        "popularity": 591.922,
        "poster_path": "/hPfWHgq07nXbeldwEGxWB4JqwtE.jpg",
        "release_date": "2024-05-31",
        "title": "In a Violent Nature",
        "video": false,
        "vote_average": 5.803,
        "vote_count": 117
      },
      {
        "adult": false,
        "backdrop_path": "/bVigVS3LVotEK4GsBlGOagkjPEc.jpg",
        "genre_ids": [80, 18],
        "id": 1008409,
        "original_language": "en",
        "original_title": "The Bikeriders",
        "overview":
            "After a chance encounter, headstrong Kathy is drawn to Benny, member of Midwestern motorcycle club the Vandals. As the club transforms into a dangerous underworld of violence, Benny must choose between Kathy and his loyalty to the club.",
        "popularity": 177.443,
        "poster_path": "/qTb6sSRt8Pw96JTan8ezU2xO0FU.jpg",
        "release_date": "2024-06-19",
        "title": "The Bikeriders",
        "video": false,
        "vote_average": 7.109,
        "vote_count": 297
      },
      {
        "adult": false,
        "backdrop_path": "/oMiKHO3H5RixfLsiU5Vumhlp5sj.jpg",
        "genre_ids": [80, 10749, 53],
        "id": 948549,
        "original_language": "en",
        "original_title": "Love Lies Bleeding",
        "overview":
            "Reclusive gym manager Lou falls hard for Jackie, an ambitious bodybuilder headed through town to Las Vegas in pursuit of her dream. But their love ignites violence, pulling them deep into the web of Lou’s criminal family.",
        "popularity": 241.965,
        "poster_path": "/p7jyFWiLyHPttqYBFAlLJwtYTYH.jpg",
        "release_date": "2024-03-08",
        "title": "Love Lies Bleeding",
        "video": false,
        "vote_average": 6.543,
        "vote_count": 334
      },
      {
        "adult": false,
        "backdrop_path": "/4yrOyO3N55XazHQXXYoqiiPQd40.jpg",
        "genre_ids": [27],
        "id": 938614,
        "original_language": "en",
        "original_title": "Late Night with the Devil",
        "overview":
            "A live broadcast of a late-night talk show in 1977 goes horribly wrong, unleashing evil into the nation's living rooms.",
        "popularity": 271.001,
        "poster_path": "/jGY62i0D0zitaGz4Ema7vTEYIXw.jpg",
        "release_date": "2024-03-19",
        "title": "Late Night with the Devil",
        "video": false,
        "vote_average": 7.301,
        "vote_count": 607
      },
      {
        "adult": false,
        "backdrop_path": "/Avtx5jsdPuDa091jvx2Lye3ygke.jpg",
        "genre_ids": [80, 27, 53],
        "id": 1226578,
        "original_language": "en",
        "original_title": "Longlegs",
        "overview":
            "In pursuit of a serial killer, an FBI agent uncovers a series of occult clues that she must solve to end his terrifying killing spree.",
        "popularity": 190.849,
        "poster_path": "/dLAP1apgFIoBoPNw4HJLVACSu7u.jpg",
        "release_date": "2024-07-10",
        "title": "Longlegs",
        "video": false,
        "vote_average": 6.8,
        "vote_count": 111
      },
      {
        "adult": false,
        "backdrop_path": "/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg",
        "genre_ids": [80, 35, 10749],
        "id": 974635,
        "original_language": "en",
        "original_title": "Hit Man",
        "overview":
            "A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.",
        "popularity": 192.079,
        "poster_path": "/5BfcYFhRVlgWLFo4SCkQNsIWzyy.jpg",
        "release_date": "2024-05-16",
        "title": "Hit Man",
        "video": false,
        "vote_average": 7.038,
        "vote_count": 559
      },
      {
        "adult": false,
        "backdrop_path": "/A3BnHM8a56lsHwn4o7ogiq1KHGh.jpg",
        "genre_ids": [12, 18],
        "id": 937746,
        "original_language": "it",
        "original_title": "Io capitano",
        "overview":
            "Longing for a brighter future, two Senegalese teenagers embark on a journey from West Africa to Italy. However, between their dreams and reality lies a labyrinth of checkpoints, the Sahara Desert, and the vast waters of the Mediterranean.",
        "popularity": 104.403,
        "poster_path": "/arh0pfq8PfyLfob4ymMz8kzrVFR.jpg",
        "release_date": "2023-09-07",
        "title": "Io Capitano",
        "video": false,
        "vote_average": 7.833,
        "vote_count": 580
      },
      {
        "adult": false,
        "backdrop_path": "/viKEEaaCaZ0hZ2nGuvIEozlLooL.jpg",
        "genre_ids": [27, 80, 9648],
        "id": 1023922,
        "original_language": "en",
        "original_title": "MaXXXine",
        "overview":
            "In 1980s Hollywood, adult film star and aspiring actress Maxine Minx finally gets her big break. But as a mysterious killer stalks the starlets of Hollywood, a trail of blood threatens to reveal her sinister past.",
        "popularity": 132.604,
        "poster_path": "/ArvoFK6nlouZRxYmtIOUzKIrg90.jpg",
        "release_date": "2024-07-04",
        "title": "MaXXXine",
        "video": false,
        "vote_average": 7,
        "vote_count": 94
      },
      {
        "adult": false,
        "backdrop_path": "/8xMR5w9qfpwhTJzjjvfj2ywvIF3.jpg",
        "genre_ids": [35, 10749],
        "id": 956842,
        "original_language": "en",
        "original_title": "Fly Me to the Moon",
        "overview":
            "Sparks fly in all directions as marketing maven Kelly Jones, brought in to fix NASA's public image, wreaks havoc on Apollo 11 launch director Cole Davis' already difficult task of putting a man on the moon. When the White House deems the mission too important to fail, Jones is directed to stage a fake moon landing as backup, and the countdown truly begins.",
        "popularity": 131.697,
        "poster_path": "/gjk8YdXpItoC1in53FCrZMFIuBx.jpg",
        "release_date": "2024-07-06",
        "title": "Fly Me to the Moon",
        "video": false,
        "vote_average": 7.42,
        "vote_count": 88
      },
      {
        "adult": false,
        "backdrop_path": "/sNBnCmF1ueoERa4uW5kh929KkRO.jpg",
        "genre_ids": [18, 27],
        "id": 858017,
        "original_language": "en",
        "original_title": "I Saw the TV Glow",
        "overview":
            "Teenager Owen is just trying to make it through life in the suburbs when his classmate Maddy introduces him to a mysterious late-night TV show — a vision of a supernatural world beneath their own. In the pale glow of the television, Owen’s view of reality begins to crack.",
        "popularity": 132.163,
        "poster_path": "/hS4GYkYpN1rfl4GIxyc02sCyfAj.jpg",
        "release_date": "2024-05-03",
        "title": "I Saw the TV Glow",
        "video": false,
        "vote_average": 5.832,
        "vote_count": 122
      },
      {
        "adult": false,
        "backdrop_path": "/7ks7A3mAO7twDOvBVE4cR8LaIM8.jpg",
        "genre_ids": [16, 28, 18],
        "id": 1104844,
        "original_language": "ja",
        "original_title": "劇場版ブルーロック -EPISODE 凪-",
        "overview":
            "One day, Nagi Seishiro receives an invitation to the mysterious BLUE LOCK Project. What awaits him there is an encounter with the finest strikers assembled from across the country. Nagi's dream of becoming the best, alongside Mikage Reo, will take this prodigy to a world he's never known.",
        "popularity": 126.588,
        "poster_path": "/ae434jM5NG2kKX1rRkG5giMhpPI.jpg",
        "release_date": "2024-04-19",
        "title": "BLUE LOCK THE MOVIE -EPISODE NAGI-",
        "video": false,
        "vote_average": 8.7,
        "vote_count": 18
      },
      {
        "adult": false,
        "backdrop_path": "/sp99ZzKz6Zv7nX95XDJmhNA4LVI.jpg",
        "genre_ids": [35, 18, 9648],
        "id": 975773,
        "original_language": "en",
        "original_title": "Wicked Little Letters",
        "overview":
            "When people in Littlehampton--including conservative local Edith--begin to receive letters full of hilarious profanities, rowdy Irish migrant Rose is charged with the crime. Suspecting that something is amiss, the town's women investigate.",
        "popularity": 116.804,
        "poster_path": "/scAU7YudKNVeZlOfgSEWntAUSJ.jpg",
        "release_date": "2024-02-23",
        "title": "Wicked Little Letters",
        "video": false,
        "vote_average": 6.975,
        "vote_count": 199
      },
      {
        "adult": false,
        "backdrop_path": "/7g7cAWKvMKnzJQCxYE4OHfx131t.jpg",
        "genre_ids": [878, 27, 53],
        "id": 945961,
        "original_language": "en",
        "original_title": "Alien: Romulus",
        "overview":
            "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
        "popularity": 95.309,
        "poster_path": "/AcT2wdiCLwRSLy7dHIwHwycxxM5.jpg",
        "release_date": "2024-08-14",
        "title": "Alien: Romulus",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/aJxmgoNtP2BH7mRYvuf7AHB0VC3.jpg",
        "genre_ids": [18],
        "id": 1302004,
        "original_language": "tl",
        "original_title": "Kaskasero",
        "overview":
            "A talented mechanic and driver, Migs quickly finds success when a customer he likes, Gabbi, leads him into the life of street car racing. But as he goes along this life and learns of Gabbi’s past, Migs makes rash decisions that might put the brakes on their relationship.",
        "popularity": 108.664,
        "poster_path": "/veLIxyQJyXq8Lf6qSbXQl0ckHzC.jpg",
        "release_date": "2024-07-26",
        "title": "Kaskasero",
        "video": false,
        "vote_average": 0,
        "vote_count": 0
      },
      {
        "adult": false,
        "backdrop_path": "/954M4NsqzxIcl1so0iFPfFQTb72.jpg",
        "genre_ids": [16, 18, 35, 878],
        "id": 838240,
        "original_language": "es",
        "original_title": "Robot Dreams",
        "overview":
            "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of '80s NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
        "popularity": 103.473,
        "poster_path": "/vSzOobYVu16MogSALNg1bjTaGc.jpg",
        "release_date": "2023-12-06",
        "title": "Robot Dreams",
        "video": false,
        "vote_average": 8.1,
        "vote_count": 418
      }
    ],
    "total_pages": 40,
    "total_results": 799
  }
];
